vae:
  data_dir: "/data/world-models" 
  device:  "cuda"
  num_epochs: 50
  latent_size: 64 
  train_batch_size: 512 
  test_batch_size: 128 
  learning_rate: 0.001
  height: 64 
  width: 64

rnn: 
  data_dir: "/data/world-models" 
  vae_dir: "/home/mojo/github/world-models-pytorch/exps/VAE/2024-08-10_bs_512_epochs_50_latentsize_64"
  device: "cuda" 
  seq_len: 32 
  batch_size: 20 
  num_epochs: 10 
  latent_size: 64
  num_gaussians: 5  # from the paper 
  hidden_size: 256
  action_size: 5 
  learning_rate: 0.0001
  include_reward: True